apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://github.com/envoyproxy/gateway/releases/latest/download/gateway-crds.yaml
    - namespace.yaml
    - repository.yaml
    - release.yaml
