apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: envoy-gateway
    namespace: envoy-gateway
spec:
    interval: 15m
    chart:
        spec:
            chart: envoy-helm
            sourceRef:
                kind: HelmRepository
                name: envoy-gateway
                namespace: envoy-gateway
            version: 1.6.1
    values:
        service:
            type: LoadBalancer
