apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: envoy-gateway
    namespace: envoy-gateway
spec:
    interval: 15m
    chart:
        spec:
            chart: envoy-gateway
            sourceRef:
                kind: HelmRepository
                name: envoy-gateway
                namespace: envoy-gateway
            version: ">=1.5.0"
    values:
        service:
            type: LoadBalancer
        global:
            images:
                envoyGateway:
                    image: "docker.io/envoyproxy/envoy-gateway:latest"
                    pullPolicy: IfNotPresent

