apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: envoy-gateway
    namespace: envoy-gateway-system
spec:
    interval: 15m
    chart:
        spec:
            chart: gateway-helm
            sourceRef:
                kind: HelmRepository
                name: envoy-gateway
                namespace: envoy-gateway
            version: ">= 1.6.0"
    install:
        crds: Skip
    upgrade:
        crds: Skip
    values:
        createNamespace: true
        service:
            type: LoadBalancer
