apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: envoy-gateway-repo
    namespace: envoy-gateway
spec:
    type: oci
    interval: 1h
    url: oci://docker.io/envoyproxy
