apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: envoy-gateway
    namespace: envoy-gateway
spec:
    interval: 1h
    type: oci
    url: https://docker.io/envoyproxy
