apiVersion: v1
clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVMrZ0F3SUJBZ0lRT090ZDNUTmV1cC9VNmlrc3F2SWZvekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREV4TURFME16ZzBORm9YRFRNMk1ERXdPREUwTXpnMApORm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCSG5RQ3ZvOTRjVmtqL0FLcGZlNUthM0ZTNFYxRkdBSjdobGl3Ym1WRDVBZHJzRXBlcUdlMzZ6bkM3T2YKVTBjb2hnVGo1NUcvQ1Y1K1g2OEllZWQ4MVNxallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVUyNE5FaXZsUUlRckRpUjlBbkUzdktMY1o3ZnN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUt2VFVWbFkKWXFGY1Q3OVFkS3NpdkdvaHY1d3ZvUGdBMU5RUm0rZHJYbisvQWlFQWw5N1A3bzhDMzRVLzZ2Sjh6WUIvY2hZSQp3dnJzWWdaelJKTE0yVVRKNVJJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://10.0.0.10:6443
      name: homelab
contexts:
    - context:
        cluster: homelab
        namespace: default
        user: admin@homelab
      name: admin@homelab
current-context: admin@homelab
kind: Config
users:
    - name: admin@homelab
      user:
        client-certificate-data: ENC[AES256_GCM,data:pfa8iwq9VYh3Bf5rL9UY0cfve9LZF4N1eq71Ekjw//RCdT/NNxxx3BjWBhLrt0tigWOwdoyClPZiS6s3qRwHZIdyk+HSvqs7D8t5xc6UNG6BxNFu8BbY86DUrrjthkAufzSp3k96NtmYbnlu6A5dNkssvp/LIMQEjpi+Qudc6WJ7wM+Q3CSzN4NIvLRFJ/rC1IgGutcYonKBBGHANy7QEpo64xBNEhlMA7fWw8xyb57aZF5tjIWOHNhU+AjHvCOktukxtcoDQT3L4QzNflTU9NE5T1salZF7gK6Eqof26z/fOBS2Km7wv7TfIITPki1wjb4lJAzSLwHIDaFDueT+yP6BzLzLuHCNmgDiCsXgSRxAhXHoAviEPjj9jh6zQgXtAl132CLbohJ5i5ooFQ45w0VpD/9NbMKJbLt3PeiLgT+lX+CIjdT7E0t5meZ2tFS1fXnBaF+GdHWvpaIu5m8S/5P2q/4B2SlSlqtMwaHQuBXItJTf1CUDg02ILjZ+RG66UXiE55h2l4gePmw+lgHQSwqRmrTwFfvOAAVCp4nvK+pS1KdYv9Ed02JQE+c5yZESFG4ha2J6L8sx/ojnKm/mP/Jy/QhVCwv4hq7VP+WhPWzhOJ5iOewnH1Eu2mJ1mNX3SkdkZO98V6jrQtHa8lqwGm2MuhsGbSFT/fyCzID439C4pux8OrALHsgeiMhtOgczkaQRuIhyTNUdjP/StzgVIP720Ks7BepXdox1MRzx0t8UYxEhHTrbGUg57bPqmU5+CfeO1iAovtcE9xJ2s+JqBH7SfGEbm+x9Jt/NqpVTGwfq96h/Gf7FDiRflJum1Z84ijY6f+012bY3QAvowEs/RJIUAA8O5vMEJRBC5vWfGrQgCtVqBaWjftLB+qr12wKQ7NAPYqQtzRPqfS9oCrnzyrknUYH8FHn3syd4M6L51oRtE2yvbGjERU9A/iBhWtIJXDocU+ab1J6l0voPRuH0Y/HX0sre5rCg0j9XGGCAVgoZkeIckqcbHjpwTpTPmysTnxytF4hy4quRIE+fBKxATQ==,iv:QAGYurABO22loh8vzb8tjCMqHVy6ZzmS//63v721rPY=,tag:jYc2rLBF5lqwdTEDrFoYTA==,type:str]
        client-key-data: ENC[AES256_GCM,data:PKRXB3j1nBP1Pw52zZLoGc+YSDHxjxiV0pUXgC0oGbPQdaDtkjbaPwqNzbmYDqJWL4sHKg3Q4Liu5Wcm6ssBWwAn0RkdM8ALKNJKvgqyPo6OHHNoJvO6tsVctm1WYblCeDe6nZx1/AD6YZH4PBzoXOeWcOC0Klykduc32L1L8tXL9BkcQN/69JszGTrI5yYazMDf+aLuEbpFb8AlucebOPezvZc+TS1U5BbicSu61wUlCwyHkTnWn4BHMKIEgkxiK1gWB6oTLH1qGHxCOJU1y2Qgjed50g76KVjd3o3VB5A1eMUVZoJcSG1G4p8HIdDTgmPJ9wrxFAGPcLC6EbZoJZ5pSMb2xtvGpDthLB5cGbVxDoHAX8tiploUbsNaDWnQtBfdldcaPxvMgjwd/5paJA==,iv:b3PGpXTq5DQsy6Y7T7f2+015WE03Fom0VBkUWkz5NfY=,tag:n65OUHQ/wJUDg59QYGqssA==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWmpyYW5NaXFkdDhzN3Bp
            eWxyMmh3T1VYOXhwNnZ4aktPejdudU9oMEVZCktEVlppSzFqUUZCMDdGUjZZZ0My
            dXdaSVBpK2J1b1BqTzdaTlV0UWpqdUkKLS0tIDNxRFB2eHdXbHNVcjNuTG9zd0pX
            MTQ5Q3NUQ2pDZzVFY0YyY21pRTVBamMKb45Bv+Is6Wzi3NGFUlPs87Ur9YxwKVRc
            jcX6aEAB8iOflxuwrfjXClXMuxrgEOpQAHTCf6//vy/LxX1gJtKb/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:54:52Z"
    mac: ENC[AES256_GCM,data:544/VlAPFDoNqHZXXdAKP/vLVr4BtTXcOJjUcC7OtLdWP7lrfRtrfMQV/42uYKcu56PoAndE4LZH8aT1B7gXkpNtZpCLO9OWybRfLPDZk6kHdDXy5sy5pudgSvNRBc3zLM3KxFsM47j8LpDnc5RvpjJyNyBPntW5STV3QN9ayPM=,iv:JDHve7csVtg1M2OEDruZo6HjR8YY+L9CM41EqQlggfE=,tag:FRhjSgyTe46fVkJihmSqpQ==,type:str]
    encrypted_regex: ^(client-certificate-data|client-key-data|token|password|username)$
    version: 3.11.0
