apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: spegel-repo
    namespace: spegel
spec:
    type: "oci"
    interval: 1h
    url: oci://ghcr.io/spegel-org/helm-charts
