apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - gotk-components.yaml
    - gotk-sync.yaml
    - cilium.yaml
    # - envoy-gateway.yaml
    - metallb.yaml
    # - cert-manager.yaml
    # - cloudflare.yaml
    - local-path-provisioner.yaml
    # - cloudnative-pg.yaml
    # - redis.yaml
    # - databases.yaml
    # - spegel.yaml
