- name: Get cluster kubeconfig
  ansible.builtin.command: talosctl kubeconfig {{ root_directory }}/kubeconfig.yaml --talosconfig {{ config_file }}
  changed_when: true
  register: install_output
  tags:
      - get-kubeconfig
