apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:04rBgk6uevFYV2DwS5Da/oGKjZJRqXWSa8Xn7sw2/Yc1nBSc8+DNF7vwGdyVclTHMFxcr7Mzq4U=,iv:Hwp9X2RWlVOk9R6eiAKGZtOxOV8NKsh5NqLcOjE2Oz8=,tag:jJ/BXggTWd15OCR7/hdvIg==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNFA5NXZHWGh0dnRWOGlH
            Wm9WeFUyR211RlRwbm84Q2MwRXdsdHZRU1FNCmgraHBmajFVMk44Qzdsd09RcU5P
            WHgzWUprR0dUak9kZzVSS0c2L0hubkEKLS0tIEJYVllVZ212RFVPaG82aTB5eGMy
            NTVmM0cvUU5xQmlDbjAvb0s1dlZHdHcKGPgn88p4o4OUNFRsjCQVhvE1Ootiqsza
            IxDYiaqKbk8+2Xj7HwWlAxujJvnZ+kB0qOXSyjyZyCP/ABd821rmFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T22:33:06Z"
    mac: ENC[AES256_GCM,data:4hTkdANmfwLM2nBs8SkP2b3pBEqT+JyO2BABGGOGVij6VAd9Ib4cKjHYAvE07IHfb17eZaUi5ra9cDdCWdwdhioynlh8CHQTvARO01xCOXC8kCxwZSwphp79ja7xnHht5bp24NcRPgR8+SbCuD+9Bosw4mLzjQ0dX1NKRmG8Qe8=,iv:vUk/MK3eu6DmeNIemKrd7ua26wz8ccRV2obSrQHVwAo=,tag:mU90oV77w0gqLUuLLzpSEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
