apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:zCDNRFThQLKxhZsWlnd/JwHIFskeCcZajCYFqRVj7r+0eLr17ik8HA==,iv:8OO6QL3vTXsMgyNtVXTvt6v+99ir2J42L5AANIP3g8s=,tag:82QwlXjP2bdBkaXFIzPOmQ==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MktOalRYdExXNlBvdGJN
            SllVSGhNaTBJcWJ1UnFHTS9XY1R1T21MQVJvCloxMFBTcDdjaTU3Q21McVlRbVli
            aXB0eTFZUG5EZVF2VEZ0QlZrWVoreEUKLS0tIDVINGpsMkVoUjdubTNVa0pjdU1k
            c3NaK1NhZy9JWUF1eERqaEFKUmRad1kKlEc32b6XLYsI+ZeVV6fz1MFpuqAXSEO7
            iGHbeQemZ0S6ShfIEn29Xsy6CtumgKU44+j3TJiybGqnu8JzN+gPBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T14:48:34Z"
    mac: ENC[AES256_GCM,data:79VOs/64+C3BHSApK3wY3lUZvPPpdaWGud/JPWj5DrSlHliBaNa87f/3/z0re4yo9KrVnmWMaYZEqn8ZEtLAJ9TQ4FDn2UsxqOGFiW/hhmKdBa9Bik2fpk9bKpD8vBC9UQAPCjoT9e9bxRQjstYaO5rHIdh1iHqlI43s0zEsMQ4=,iv:gDnHQVTGx4ol8b+JoA8ud0eC+Z8Dva0Dr97C+biOecE=,tag:FP4gSkVgqJUYun+QWxW4bQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
