apiVersion: v1
kind: Secret
metadata:
    name: config-json-file-secret
    namespace: cloudflare
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:i5joYyc5mK9w8QNmrmfxCGOQ+jxSKh/ZE7qPKkj6DF66Qtr3cDLvDZACPEEx6dQCZhY8K1EO0Ww8g+6DjBjZacWiOS1MKZnQUUvFByr7mpxHmlE4UhFKd257/LCRZ5Q2fOfEAYEvKW++LwhKDrubPYkyOHb+dFU3l3PnhVpyuN3OqX2Sg9IQ6MT5+Q2Kagpe0fc4wy8UNs9fKvXp2QuI7OjvKyFc4w/UtqYcfiAVICQR3VjrELAM0WHJ/JzaTJUyIqqtpwU+hvyOhw==,iv:fXO9PjasOgv4E5rze0bmIhEmWbuP4g/5VU5rX2NNHg8=,tag:N+cTI5/csJrhzFBNLuWFhw==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVg1dEpDcExPSVU0VGRn
            YVFyZ0d1YTQzZUtybzVoWjR3UGJYS29sZUhzCnV0VnJDS0Q4MEV3YzhQUkRITkk3
            azVLd0hXSlhrMFNxMnVWUFRLSGpVekUKLS0tIG1POHAvZ2dVYklEWXNMMlArdjVV
            T0c2dXlSUVBSNTNEVjVlMTVRQjJxQnMKZEuTq222Qm4JHdDz3atttvfFYlh51Xua
            55eq+NhaBwgOrnbkL6whPZqx1mGrCBA+2nKLgcCc+mCD2G2HJqX6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T23:42:40Z"
    mac: ENC[AES256_GCM,data:cdWRGiD5wUr9ikuv3Rb2BRrdqQkWfhWRzKia0s1a8Z/ydgqxHPgGMsmkVPRRobMog2rvvD3Gkj3hMylOT30XFhzs6FmoKpjsox0CkYz061YAeIsiROlqR6zqjEh6t6bRsVChez0lpsCjarSwtN5j230V+b5q6rlYN6g1UgsWlGA=,iv:WRJ2HdcrHMOcwMdRY0CI1Wr72A4k6wTG1yAQHCCVYe8=,tag:OE7DRO3f30RlaQMa13SbjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cert-pem-file-secret
    namespace: cloudflare
type: Opaque
stringData:
    cert.pem: ENC[AES256_GCM,data:7KGF8Wc0/SDq6JhPAQaEh8WLYdLPuFq7O7pDYIYlPt64IDWvkgyozTdIcjrIZ/21qhQnjdAbLk2CRwlbvS+fH4Xkcb4LgsLUgugmfWvdpAb0UPRaZODJl2h5YMfGTfkORhF3Zc+VgUQT8f7kynAf16UiVYDCyjWOZRd6bWffFaym540uw8Pgt9BeCHMYaFCAbZutCdhFLkKMCAEP7otnpQwT3WeAeOM2UlidfexPUdVXAOOxq3e+rVQPjAuJqMdwqn+viCWTOAbsLQ+W9Ra6a8Z3H6QOsN35JYqAo4ZSaz/mZo+V8qzw86zLRfRAhcJhqtHKLCk3RN/PulzDgQHw0kYIM9QF3Pwhbmg=,iv:4LQLmutODqU/Wd/3XIxrPbFGZStUVmbhevoOe4AJmEg=,tag:UryHaQdD+BGiNjpHVASW/A==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVg1dEpDcExPSVU0VGRn
            YVFyZ0d1YTQzZUtybzVoWjR3UGJYS29sZUhzCnV0VnJDS0Q4MEV3YzhQUkRITkk3
            azVLd0hXSlhrMFNxMnVWUFRLSGpVekUKLS0tIG1POHAvZ2dVYklEWXNMMlArdjVV
            T0c2dXlSUVBSNTNEVjVlMTVRQjJxQnMKZEuTq222Qm4JHdDz3atttvfFYlh51Xua
            55eq+NhaBwgOrnbkL6whPZqx1mGrCBA+2nKLgcCc+mCD2G2HJqX6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T23:42:40Z"
    mac: ENC[AES256_GCM,data:cdWRGiD5wUr9ikuv3Rb2BRrdqQkWfhWRzKia0s1a8Z/ydgqxHPgGMsmkVPRRobMog2rvvD3Gkj3hMylOT30XFhzs6FmoKpjsox0CkYz061YAeIsiROlqR6zqjEh6t6bRsVChez0lpsCjarSwtN5j230V+b5q6rlYN6g1UgsWlGA=,iv:WRJ2HdcrHMOcwMdRY0CI1Wr72A4k6wTG1yAQHCCVYe8=,tag:OE7DRO3f30RlaQMa13SbjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
