apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
stringData:
    cf-tunnel-token: ENC[AES256_GCM,data:IF7RsP3qjgGYfgQxdksIdjMwvTgPO2JxOLnKdmw2pOYFTCPeLXcoaVzFVWgJvchiH0lxHMKxM/nPnHJe+BoUaO2V7a2/G4r7q/YxwwYuO57So4LoCwe2mgwBW50Sywh3QcXAYfiIoBOmHht7ChVKBgywETKo9cCYn1B2eK9WP9Qa69x9lnu8ZyYvk+ENP6+VHXYhnEjVNIvC6uit0gFcVMAlwIVqt4qYQ3PGI832JIkvSy89lNt0wg==,iv:CpYdZcnKG2MQxLQpZ7ScV3oAKnjjx7g8vS0yCBUdN+Q=,tag:mbkMyoHpAmhpL+hbt36FYQ==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMHJBV3ZHRTRJS0hhTGwv
            WjBMNkdUOVZ4U0wzY0hnT1BLYUVFUGYwSlVZCnAwNXVxZDJGWWlIdklsc1JsUCtr
            VlRkNmRwU3lCRFE1MFRYd3UyMlJaV2cKLS0tIEdvTGxFN0tQZVFqQ05teWxOVEIz
            azdOWEkvdU9ZNk5PVm1WVVFaVHNPT2cKUoZ6mbDWPQKWEra6ZUWHVgUmmAsI8/eb
            qi7azVdlH6BVXiPHioN6e2FXlhw2UMr+ZbY0nNjctJY/eXHW0U88aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T21:09:28Z"
    mac: ENC[AES256_GCM,data:d6054j27jvGrhrf+ifGr2B5qYour6Pypn3QY6G02bkCMopsx4ciesB7rDDBddgGFM/BH7nbRTvOuTGkbQirg6cJk/brSwhYxYJOt3JlXxX/aQu6utl/70LSrowbvRcBkUiYgJm+9LQlOMx7nKfKpGlXWIz8yYbNs3lzmBn+xbH0=,iv:vcessH5Z5JTP0x/k5MfCrhdTjrfKPR2YHms8pc1OuhM=,tag:RU7uyB39IUr6hKq/Xzwn8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
