apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare
type: Opaque
stringData:
    cf-tunnel-token: ENC[AES256_GCM,data:ue1VXu4vZt6iF/Gw+l2T+bD2aTB3POijzJsajROnVPhZ8TUqF7MdB5xjTEOWI02zlJwIcci2V28MeLqDSywUi7TrDIuckf1Wpf9vTyG8AiGfAwb8H5FNlIZbQOFUkutniodc0ApCLTbp9fqJAYUZXXPK+ovzcmArabLL/YPVgMn+bzbEfWSuqbyD8X92Wmkx0mSny+eEM3pBTm2jpA1IQULB4L6535F0lpVgoTDkX+nTtotY4ns/oQ==,iv:9Z5PF1B06ySTx0ArAJj5UvkItXOmVsLGW+pYPBa4sKM=,tag:xiiNMssWBUA045bdg6y9CQ==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZVBoMjIyVDdUMTBMSWxn
            OWlOd3JsUTJBRmlOUklEU01wY3Q0L2dYbnlrCmpnLzAyZkwzdlhZbk42bVVWdTBE
            VnNGanRkYU1qckw4d3pIVGJBSVlJOUUKLS0tIDNTSFdNUkNwd1JNYzNXTDFXOUl4
            TUdheXA3QXVwRWg1MC9vRUtoTDZKbGMK5VEd60p3s6b3F3Yb+NYRz+r/yrLxpt3E
            bfj54q+ubqivaZTVWJGK06ogcxr/u/IesvyXrEPx8WSLaha1RUWxMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T00:09:20Z"
    mac: ENC[AES256_GCM,data:DHYqN4vyevSinyhUFAz0Vqn+EHmOeVqGSf+qJR8XzPVLy9qOUaz9SwoMQz85xtISgWAy8qTXgWFL65p8/HuszZF92tmueX6kXjSFsLGHPNEp8ti+yTADHxhnVLoY1KCW4lCTfVz6delFLmAL/yWVe9DopB7Ijv32siWxYDZXEzg=,iv:zfRNvHraJi4SbhEHVEvH+5C9FEfq44FIhqi84Q1Wzes=,tag:Rga/FVTccPlmiBXYir3irQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
