apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
stringData:
    tunnel-config.json: ENC[AES256_GCM,data:G4ck7B94uw12+ke4e1w3Nb/NwPftoE9JkmpQuMR5qqMPFHdwvMJ0oR3tLL1Jsk1d9n4TUGTyYJp6HPag8x1u13ksNyrsAgwnxUd3kbu3OB75vHW3Wy7uv1cKT0Ca0Oy/v/VaIteCP8yroLuQxBdG7JCiXuIN/DOaI7LvhgS69rOF5UBFQ5aajSpERJ4reOmJveNOgsukVh9uBn+duymism3qpGE83JNbzgFGjwef7dR7WiCf+JCNRypXZlFK+5wD+rmSvRLy3d01VbtwbJpQivfQHfxDkg==,iv:L0mNKQBu4Q0euDUbCH6PWJ9XHBZ0ogu4UcO77QWWpuE=,tag:csRfobxB8p3xeFDRC4sEWg==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLK0VTMWJUS1M2eDhDMzZE
            eHBWVnRObmF5ZzVBUDJjZ3JzcWsvYlRWNWdrCml1Y2FpdVpUTUwxQlpUd3VDUThz
            V0dDOWRrMzdzcjcxcHdwNVhQVVRhdEUKLS0tIDZQRFYwSFR2Mmlvb2NuMGRUV3FD
            VkVGOTdQdkN6cklYSUFoYmwrbkk1UEkKvzsDnuwESe9BXx3HgGYoD2jaleLR/B+C
            DfEFn8j5tfZ0Hti+B3/Jf1NRRHDGrOCH81QobldkGjVjvxwQPykCwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T13:45:18Z"
    mac: ENC[AES256_GCM,data:j2z7QNALRLvTfW1dYsl8wQpgdp1U8hwD5JdjlL4JTz6KiWcFkfFgLQAK1hFJajIpqu3EWt/FJOMsdJsWcvDzDH9Xacs2LTzuiIqOvWdPSYKoRevfkmFbsV+r6lwTp2yS7uEPpnOUXcMwsTeLmiJ3/aZIICR1Q/D4r1kksiG8cxk=,iv:xSN04pYHNUVRaO1lWNa0BC6EgA1UOCttlvYVYUyYMBk=,tag:l0FddI1HRn35aAQNxoRySA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
