apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
data:
    tunnelID: ENC[AES256_GCM,data:E+erSPS/6rYuKvCBu9dlv0ahZmi3HjHePth+eCHR+CadWyDuT131uig53A54E1KH,iv:xPj8c3AAEJImGqXXEsKhDA09iZ8Q6V1DX2NvQ9AMuBA=,tag:4ay3aDlaKuUTdMQYx+jSNw==,type:str]
    accountTag: ENC[AES256_GCM,data:wrfFqbiRs07lfm7IKN0y2UfQCSPSimB/7z7bY9pUcL6G+RLyUjN5kuPIgR0=,iv:LMwmSvO8wvFVHBxG+22iCSBYdedkHIqpUzi4SPuIAjM=,tag:9Cj7Hi39TdXqbwOeAvoPLQ==,type:str]
    tunnelName: ENC[AES256_GCM,data:5cBVD19BGs3FaqZOT8pMktRpbXmvdDE80M/NSus788s=,iv:fUUQ43f3EQGskPJqzCwfnyKtcPpFFht/f7mIupuXJms=,tag:J0uUHz+gLLAh+DY7dudcrg==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:1CEyfDZD4LZE2oXn5v343tPDDBt5MtA+0dydsx9Rxm+KbH4jcSaSO7HP1gj5X+1s9HJ+e+4ZyEBd3oWc,iv:GjW0r0Kgpr4nUtX6Sa9rTnBPEXNDqpqhgJC1lkTyNk8=,tag:kEONpb44OJHeRL848O+k1w==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL3YzbzdtazdRSDdVUFRW
              ZDVXdzNLdFluQUZ1dDk2eExWTzZmT3lESDJZCm90RUZNdjVlRVRHaDBYTXUwczNW
              L2MvRklYUGZMTHFDZWJrTEIrcGI4d1kKLS0tIG05MElKRW9iWHh1OWZuWGlxbjZV
              U0ZyelZ5WnZFWHYvalhLYWpjZGpHdU0K8MZfopMA0BDwpE1DnJGZAcKVRR3adP+F
              N9X29JRFuX5wqOohPar6hJLuDxov9MuVXiUVgjo88vqX819F00hZbA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:09:03Z"
    mac: ENC[AES256_GCM,data:KVahYTOJZcH5kkoMWDkEybw716TFs0YwoxtmSKd5Yw8lNHybigHWjpRAs7QsllUh0Kis8/y16TUe82SMn6imul7PtXyPb3VgnmK4d8bjQYoYZ0PIqM73Y+63Ybd0CJv2nKOerX18Jfq9tAlRGP3z9rYrJDHNd1x7H3Qe+jgMGdU=,iv:apCjipSLb1IUIW165T0Ls831e2OFS1eOAVBfP7n3ZR0=,tag:9MQgCe7sfN2coKxVOGuTJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
