apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
stringData:
    tunnelID: ENC[AES256_GCM,data:dlHpLJrLMRVCryhe+ZmXaFwyMvNuFpjR/w1k60/Rdkt1kdE7,iv:nMsFIqvAMu4ycsrGJ9J6zUEJveuYkxPkAkCYxWx2bzw=,tag:TBaHBSpd0jxXLyOp8x2doQ==,type:str]
    accountTag: ENC[AES256_GCM,data:0joNiw85oe6GTnHcB+HbXP0YcMmkrkSypafjT229zlY=,iv:wYdznI6rhRIQ06HLESqzELcfvA5Qf/EY8I+tOF3qf4U=,tag:yYThUzIxAxbCqzEp785OQA==,type:str]
    tunnelName: ENC[AES256_GCM,data:+9xypDX2acTqWvD8iEG4T0Q5gbKu+w==,iv:Jc11mhRw7c8ccHlNbhJAyVnlkf33pos0yn4qbBF2FiI=,tag:JBOg7KCrejrU1XNP0M4AJQ==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:f+fDQTHrgAU5WZYjezV/Dxuv2XlY+OIyXsbo9AspmaCeh+c7zvpzq7lDjV0=,iv:NdLquQAT9ir1hWgH2sQIM1gjn7p+u5KrI1FadGVWGOI=,tag:1ZYK2drpWZqjzrbMjWnYTQ==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMTMvdVNjR3U5QlAwUFpN
            N3dkaXJUaHFBUXR6aHdONUJPTDRLd3hZWnhNCjZQMThtOW1QQWZjc0lTbzEyRllV
            ZWJkWGpRYW55VVBYQzZWM0RjeGZoZ1UKLS0tICt6UEN5azJicFFhODlzaHZkdWQ3
            L09qZy9lL2RtYUNXbWh6c3hvVUZuZmsKYtLEf6h8aCaavS5oG2bFU+Pwtvmguk19
            aLvsZsqvZXzO9YBFfVIfO67qLXEmO6pyaZSBE/gtHZy+Dnxt+IpX3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T13:52:50Z"
    mac: ENC[AES256_GCM,data:oUUS8nWVhihxARl2i2JYgh8m/7jPH4oa9AYH9Wt4wk3TiOLVfGD6zigFsJxPCh6KK27pJTis67aPqVRV7LCGtouDbubmAbQNtMyAAKcqqCHjDf3PT96qyprzC4Z9xsMsU41cO9lVDgSYAqR8cS8+DLbS/zju+0nyyAl9x7T0Q58=,iv:5qYmipDz9FtKQXcPJKILYagzqwq1U8naUoj/G/PRkGM=,tag:9iawoTNJeCHH89uvyuamFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
