apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
stringData:
    tunnelID: ENC[AES256_GCM,data:MRpySP/j0eVreDzNY7eWSIUmq01P02TPMrtv9zS3d3S2yNQQ,iv:zndchRE0rxAqd/+3IOtsouv0JUNvIWhIq5IN4MEeVqk=,tag:dN9neCBW14i/JKYiISE0fg==,type:str]
    accountTag: ENC[AES256_GCM,data:XEFAeYOWiDTk7g7Fvur43Mhxm1uUjJlLQzkNeREP7WI=,iv:tYRvfRSqnhveHFGm328aNpBRQPYGWv3Wy9hxcEkpzew=,tag:FOY/RRu6u+kvGT+7kjOjVQ==,type:str]
    tunnelName: ENC[AES256_GCM,data:oPCzx3laT76CCm4b4Qrer/WTfTsXKA==,iv:Wa1+r6FOwcqmvqIFe0RkUaOIANJo+uXRYfaUptrWYZU=,tag:nf32GqUXjJbYZR4VoKBtpw==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:ws6aV+3IQTczxcowvtNlF7JX3zbGMft0wMZhtY2/AXpHXKJ3zQSPrqtFLhk=,iv:1yz0QAszvcKQnUA51OUWkiWol8ZH4L9k+cN3i2+VTMw=,tag:iecIhpgqXX6oz/BW3w2R8w==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXFEdDJoOXpzak8zM1FX
            ckZPZFlLSWNZdnVqMUh4TGFYZld3disvamxJCkJqWG9oNGZUWlBPdGpGMHpqak5D
            TldZcWJsTk5HV0FsZHl6cWpkblBRelkKLS0tIEYzYUZkQkxKZHpqV2N4TGRUMEtX
            SnFxamxvK2gvc1FWQkRYaklqUzZ4Y1UK6c1UrS62aki3D/Y2HW63E6uoadJkXIeK
            r/WA3A4Z3RNoFDQQlHpbFcm1qS2ueMToclZw0sEgdk7dCyTXiDjMKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T00:36:51Z"
    mac: ENC[AES256_GCM,data:2g+OTzwsPYMGeukYJR7XvUWFiLyWmYWkVpT2vI/rqNwFIrBWfv2dJYFsE21iCG7jFBn23dvBufoGQafF36G8HmjSQ2wohwI5pP7Gtj0ZfE85WAN07BFHz/HpO/VTay2EgfJfs6/Rn8Q8oVm1eqxS6bA2ZyfOzs6HOacMJ5Ydq2s=,iv:dk/B6Ffdv3WZ+RSE3JV91/++kxPlx4+OgOC3uV6zy/w=,tag:ZTPORmkv7v1JSnTqalIwTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
