apiVersion: v1
kind: Secret
metadata:
    # IMPORTANT!!! secrate name has to be the same as service name
    name: cloudflare-tunnel-remote
    namespace: cloudflare
type: Opaque
data:
    tunnelToken: ENC[AES256_GCM,data:TEdoxZYjwmdc6fWYkaTJkZa/unYrv8YdMlgY//v1gG1Wle0gogz66By5/CZK9cY+zVXTeBZfn7husOchPgZOapoDuKYkcLFtowt+upC8++8DuH5/0maK4N1xXZdeOA+oIos09mkMRj5ix1Qm/50gq7MqKz7CkHDxL0vsK8a9znNHvvgWmP524u96A74Hlf+mZuTgq8cbW9Yl2xIkKz8OfBzF6fPMK4HLhi2RUw5w9BOhJz9Al0B2jQ==,iv:XHcKhiPRvlMmx/L/lrjywo7zwmj2vltwDabXtvrtm/c=,tag:PIneU0ppp9OP+iUtLN8fbQ==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VXRUSjBEQnVHNGdMMk9s
            QzlQUmp0dGJ5NVQ5YlRNZGV4cW1HOGJRUWhjCk1TRUJUVTFFdGpwODhjNG1GcDZv
            MGNiOGpRNitPOWNpTklQbUpPQkZKbm8KLS0tIFh0ZFE0ZWU1L2RzR2ZteEhaWUp5
            Nmxwa1pTbGxRWHlZVU5jaWlqOWU3MkEKJFzlFkwvHDlZmMuzuwW/CrhtcEiXIaca
            zkYBdmiILpXxEs/ux4D86quAj2BgX7YrI0eeEdX6b7PyYNWVl/VYOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T14:25:16Z"
    mac: ENC[AES256_GCM,data:VDYMA3tSC+PZpi9EPfsbYv1Kyqm8T/pZ/AzUEbaSV7/RgZUfm0fVTI5qViV6S7OJT0f4YokuarnzyxaFPBgDlBVhu8v/1q5FSd0rulYmUj0KzGxzfRP2ZsPk2pz1s6ZPaqEt058RceiDWALt4KT/vfBLUqo10UFyQoy1Cr+bxLM=,iv:R+qmzWeSJ/clfAye53LYo09BcXas1CKe282MU8CJqOY=,tag:h/KQJJL8bpyjFS1F9no/0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
