apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
data:
    tunnelID: ENC[AES256_GCM,data:0n5f/TigpMB5crInMX6Izy8MY/QNStaVOzMspMWhjtN+jsFaftViFzs7bNrgFLBl,iv:8pRA5ikM4rQvVdrpS76umRvkzZ1XWZDRtt5gTfSQdxg=,tag:gD8QjpXF44dolKcIuUgwvA==,type:str]
    accountTag: ENC[AES256_GCM,data:abrtzrEUpy+hIUe6R+VlMyi7IFwzA+uE5UkFtFsVK0HOba+FAMRFnGoDV/s=,iv:JmhSSAp91n+okO7u+rhUQZLboy/U7jl/X9MKckByzpg=,tag:jfqrQrpx2l7ocmHrmu661Q==,type:str]
    tunnelName: ENC[AES256_GCM,data:nkcPyAZYDPC4+Y8FzI+avNcFaIzjmdL2jxthNdZOIt8=,iv:efAK7tKyR1g2dt7mQOXQhCHNLyELFcy7l7OZcNPnMys=,tag:M4h66AHSuPm4fzttXTzDVA==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:osMcjp//hsz767FYFp/F/DTiCuvVQvcLb47YtYpk0HDl7Ycue/XRH8O3Y6vN3lxtAheuahctJvVR4HmF,iv:xP3KXKV4AMyHeFCbDbGjpTtfnZ/b68ziwShFSTjClZw=,tag:yZmZbUih381JHVuSjGvmhA==,type:str]
sops:
    age:
        - recipient: age1hl26th0hzlghpj2rmgxuxt0eqmdvngw76pq8q5tp3mw0yxkmmvqq67khw8
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbzZpQkdPY05LdjVhSEwz
              b1hUdUtheU5FSCtzNzlnSy9IU3hpYkVVZFR3CndERFJPbmltUThsZnlhL2J0Wms5
              d3puLzRHUWZwUU9BZ2hGcnNGTTdYMkEKLS0tIEUxNU45WmxFNUprT0RpK2tOVk92
              cVkxNE1OQkZmdUR0NEJIVDdKWTRnVDQKoQwdcrOGi3PJRCzvCghj1nN+gXGFQVMn
              JZ4A/f0a8+KqTqz1Feh8ZX8FpbNspdX2t8K0fS1qbNeLw3t5mBTAlg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:21:50Z"
    mac: ENC[AES256_GCM,data:7g4Hxu/o5yp147mDQ+4BiFYMt/wxmYMuH7dYyR+Q4rnhB/0OMv0FtWWsUb+TOhqbrZ7Zx8h12RaJmUSQRqrpgi/3g3avPxaO4Tmgtcz9iXfkU5hRYUgsYsIOt5Fz0lZ+I2/+OZmkIHL+tF3kOoCNQyEyVfQjgsYhX/8kvNvtvcE=,iv:SrBhNwkqC2cYyB7ZHFnxMGMvKPT4XRkHVRyWOYRBWFg=,tag:4+lbtztYFhr2PliftNFsUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
